apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generatedby: hurtle.it
  labels:
    app: sample-so
  name: sample-so
  namespace: demo
spec: {}
status:
  dockerImageRepository: 172.30.172.8:5000/demo/sample-so
