apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generatedby: hurtle.it
  labels:
    app: hurtle-cc-api
  name: hurtle-cc-api
  namespace: demo
spec: {}
status:
  dockerImageRepository: 172.30.172.8:5000/demo/hurtle-cc-api
