apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generatedby: hurtle.it
  labels:
    app: hurtle-cc-api
  name: hurtle-cc-api
  namespace: test
spec: {}
status:
  dockerImageRepository: 172.30.33.47:5000/test/hurtle-cc-api
