apiVersion: v1
kind: Route
metadata:
  annotations:
    openshift.io/generatedby: hurtle.it
  labels:
    app: sample-sm
  name: sample-sm-admin
  namespace: demo
spec:
  host: sample-sm-admin.demo.apps.opsv3.cloudcomplab.ch
  to:
    kind: Service
    name: sample-sm-admin
status: {}
